### PR TITLE
added automatic usage validation for required args

### PR DESCRIPTION
**Pull request by mstreuhofer**
If the environment variable USAGE_VALIDATION is set to "true" an
automatic validation will take place which makes sure that every option
which requires an argument was actually specified.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Does this address #48 ?

**Comment by mstreuhofer** [comment]
no. all it does it call help with an appropriate error message if a required option argument is not specified.

**Comment by mstreuhofer** [comment]
but this might actually address #22 (if i understand it correctly which i can't be sure of since the reference to a very specific code line is invalid by now).

**Comment by zbeekman** [comment]
Haven't looked at the code yet but excited about a great feature!

**Comment by mstreuhofer** [comment]
PR #63 is more important and the two step on each others toes. so i'm closing this PR here for now. will come back once the dust settled.

**Pull request closed without merging**
