### PR TITLE
added automatic usage validation for required args

### LINKED ISSUE #22: Feature Idea: Parse usage block for "Required." to allow flexible require specification
Not sure how hard this would be to implement, but parsing the usage block to find the "Required" arguments would eliminate the extra code at line:
https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L234

### PR DESCRIPTION
**Pull request by mstreuhofer**
If the description of an option contains the single word sentence
'Required.' it is understood as a required argument and automatic
validation will make sure that it is set or end the script by calling
help.

Alternatively, if the argument within the __usage string is {arg}
instead of [arg] it is understood as a required argument and automatic
validation will make sure that it is set or end the script by calling
help (even if 'Required.' is not in the description).

Closes #22

### CODE REVIEW

**Comment by mstreuhofer** [comment]
referencing PR #65 here.
this branch already incorporates the changes from #72 done manually because the first try (where is rebased on the branch `vade-retro-eval` broke github somehow...

**Comment by zbeekman** [comment]
> this PR is already rebased on vade-retro-eval assuming that there is no reason why it won't be merged.

perfect, we'll deal with #72 first.

**Comment by zbeekman** [comment]
oy vey... I thought that we could just merge #72 and then this PR would update to show only the new commits/changes, but unfortunately that doesn't seem to be the case... any chance you could rebase just the changes for this PR on to kvz:origin?

**Comment by mstreuhofer** [comment]
that's what i was hoping too.
i'll see what i can do to untangle this mess.

**Comment by zbeekman** [comment]
if not no worries... In the past I had thought that this worked, but perhaps they changed Github

**Comment by mstreuhofer** [comment]
but you know, github can (and did)show only the changes of the second commit if you asked nicely. so if it was just about the diff that would have worked as-is.

click on "Files changed" in the PR, top left you have a drop-down where you can choose to see the changes of all commits or only a single one.

no matter. i cleaned up and this PR has now one commit dealing only with the changes for automatic validation.

**Comment by zbeekman** [comment]
> no matter. i cleaned up and this PR has now one commit dealing only with the changes for automatic validation.

Thanks for accommodating me.

Can you tell me about the two new files? These are tests that you wrote? Did you generate them automagically with @kvz's testing infrastructure or did you manually write one or both out?

**Comment by zbeekman** [comment]
@mstreuhofer PLEASE DO NOT TOUCH THIS PR (until I resolve issues discussed in #75)

**Comment by zbeekman** [comment]
@mstreuhofer OK, great we should be good to go here...

**Comment by mstreuhofer** [comment]
@zbeekman i wrote the test, made sure my code works as expected. then used the save-fixture feature of @kvz

**Comment by mstreuhofer** [comment]
also: this PR feels happy to be of service in resurrecting the master branch. :)
just checked with my local repo and as far as git is concerned nothing ever happened.
good job! 👍

**Comment by zbeekman** [comment]
@mstreuhofer I like to think that I'm a git magician/wizzard: ✨ 🐇 🎩 

In reality, maybe this is more accurate: :neckbeard: 

PR LGTM!

**Pull request merged**
