### PR TITLE
Add magic variable that stores the full command line invocation

### PR DESCRIPTION
**Pull request by gdevenyi**
Add a magic variable to provide the full invocation of the script. Intended for logging purposes.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Forgot to mention, stolen from https://stackoverflow.com/a/36625791

Main reason for not just $0 $* is maintaining the separators properly. (as described in the post)

Looks like travis fails due to ruby install broken. I couldn't run the tests locally because ruby is a mess.

**Comment by kvz** [comment]
Ah I see! If you can add that attribution & explanation I think it's certainly helpful enough to merge!

**Comment by kvz** [comment]
Thanks! Maybe it's nice to have the attribution in the changelog too, and maybe a comment directly in the source, or something explaing in the docs about this magic variable? 

But I went ahead and merge this cause we can add that later if you agree

**Comment by gdevenyi** [comment]
I think the changelog is fine, but yeah, should update the docs in the appropriate place.

**Comment by 2Shirt** [comment]
This change causes an unintended exit. If there are no arguments passed then `$((($#)) && printf ' %q' "$@")` is caught by `set -o errexit` and the script exits immediately.

I suggest the following line instead:
`__invocation="$(printf %q "${__file}")$((($#)) && printf ' %q' "$@" || true)"`

**Comment by gdevenyi** [comment]
Oops, agree, that needs a or true

**Pull request merged**
