### PR TITLE
WIP: Add color, function name and line numbers to debug mode

### PR DESCRIPTION
**Pull request by virgilwashere**
## :sparkles: Add colour, function, line numbers to debug mode

- [x] feat(debug): :sparkles: add color to PS4 prompt
  - [x] use `strftime(3)` formatting
  - [x] standardise timestamps to UTC
  - [x] save and restore TZ if sourced
  - [x] perf(debug): do not `xtrace` log function
- [x] refactor(err_report): :hammer: prevent potential ERR trap recursion

- [x] docs(changelog): :memo: changelog entries for debug mode

## Tests

- [ ] :white_check_mark: `main-debug-ps4` scenario and fixture

reworking the tests and fixtures.

- [ ] add "change timezone" adjust

## Closes 

- #103
- #105
- #107

----

PR created with `GitHub Pull Request` inside `vscode` :grin:

### CODE REVIEW

**Comment by virgilwashere** [comment]
Very unappealing list of commits, badly `rebased` and `squashed` 🐼 

Will attempt a squash again from GH interface.

**Comment by virgilwashere** [comment]
💢 ... 💭 `v3.2` ... no `printf` on 🍏 `osx`.

refactoring

**Comment by kvz** [comment]
Hi, thanks for the work on this one! Seeing failures in both Linux and OSX. Expected?

**Comment by virgilwashere** [comment]
> Hi, thanks for the work on this one! Seeing failures in both Linux and OSX. Expected?

I'll squash the travis mods back to minimal changes (just the whitespace I think)
Shellcheck install script can be a separate change.

The Linux build will pass when I clean up above.

Having a problem with matching the expected vs actual output for the coloured debug on the OSX build. [Travis log](https://travis-ci.org/kvz/bash3boilerplate/jobs/551700206)

[Lines 4038+](https://travis-ci.org/kvz/bash3boilerplate/jobs/551700206#L4036-L4039)
Expected:

```diff
< +	{datetime} UTC {root}/main.sh:400 	 main():	 trap '__b3bp_err_report "${FUNCNAME:-.}" ${LINENO}' ERR
< +	{datetime} UTC {root}/main.sh:404 	 main():	 [[ 0 = \1 ]]
< +	{datetime} UTC {root}/main.sh:409 	 main():	 [[ 0 = \1 ]]
< +	{datetime} UTC {root}/main.sh:418 	 main():	 [[ -n {tmpdir}/x ]]
```

These 4 lines are the expected output, but are being mangled somehow, so there is no way that [line 4048](https://travis-ci.org/kvz/bash3boilerplate/jobs/551700206#L4048) can match.

```diff
> +	{datetime} UTC {root}/main.sh:> +	{datetime} UTC {root}/main.sh:> +	{datetime} UTC {root}/main.sh:> +	{datetime} UTC {root}/main.sh:pdir}/x ]]
```

From `main.sh:` `400` through to the `tm` in `{tmpdir}`

Any ideas?

**Comment by kvz** [comment]
> Any ideas?

None :man_shrugging: :scream:

**Comment by kvz** [comment]
I fixed a number of issues that caused issues with the master build. Wondering if you merge master if this branch can pass now?

**Comment by kvz** [comment]
Closing this due to inactivity. Feel free to re-open!

**Pull request closed without merging**
