### PR TITLE
Issue 44 issue 21 issue 47

### LINKED ISSUE #21: set -o errexit causes problems if -- option separator missing
easy fix, just need an `||true`

### LINKED ISSUE #44: optional error trapping
Allow debug info with line number and function name when ERR signal is raised:
1. http://unix.stackexchange.com/a/39660/84740
2. http://stackoverflow.com/a/25380229/403516

### LINKED ISSUE #47: Add CTRL-C trapping
We can trap CTRL-C and call a function in bash:
https://rimuhosting.com/knowledgebase/linux/misc/trapping-ctrl-c-in-bash

``` sh
# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
        echo "** Trapped CTRL-C"
}
```

I don't have a use case right now, but it's definitely helpful to allow graceful cleanup of an interrupted script.

### PR DESCRIPTION
**Pull request by zbeekman**
Thanks for contributing to b3bp! As part of your PR, have you:

- [X] Added an item in [CHANGELOG.md](https://github.com/kvz/bash3boilerplate/blob/master/CHANGELOG.md) with attribution?
- [X] Added your name to the [README.md](https://github.com/kvz/bash3boilerplate/blob/master/README.md#authors)
- [X] Linted your code? (`make test` should do the trick)

Fixes #47 
Fixes #44 
Fixes #21

### CODE REVIEW

**Comment by zbeekman** [comment]
I untabbified `main.sh` and `test/acceptance.sh` and added poor-man's style enforcement regex to `test/style.pl` for checking for tab characters optionally mixed in with whitespace at the beginning of lines and for trailing whitespace.

**Comment by zbeekman** [comment]
@kvz I also enable weekly cron builds with travis to see if anything in the node/Travis-CI ecosystem changes and breaks our tests... not sure if this is possible/needed but thought that it couldn't hurt.

**Comment by kvz** [comment]
Nice work - merging 🎉

**Comment by zbeekman** [comment]
posting a new release anytime soon?

**Comment by kvz** [comment]
Will do so right now

**Comment by kvz** [comment]
Done

**Pull request merged**
