### PR TITLE
added automatic usage validation for required args

### LINKED ISSUE #22: Feature Idea: Parse usage block for "Required." to allow flexible require specification
Not sure how hard this would be to implement, but parsing the usage block to find the "Required" arguments would eliminate the extra code at line:
https://github.com/kvz/bash3boilerplate/blob/master/main.sh#L234

### PR DESCRIPTION
**Pull request by mstreuhofer**
If the description of an option contains the single word sentence
'Required.' it is understood as a required argument and automatic
validation will make sure that it is set or end the script by calling
help.

Alternatively, if the argument within the __usage string is {arg}
instead of [arg] it is understood as a required argument and automatic
validation will make sure that it is set or end the script by calling
help.

Closes #22

### CODE REVIEW

**Comment by mstreuhofer** [comment]
yes, i know. we need to discuss this.
the automatic validation runs always, even if the help is requested in which case it wouldn't need to bother checking other options.
But -h could be redefined to something else by the user so what to do?

to make the test happy i changed it so it executes "main.sh -f /tmp/x -h"

**Comment by mstreuhofer** [comment]
in regard to @zbeekman 's comment:

Right now we don't support mandatory options without arguments (in the sense of making it clear in the usage output that a certain option is required or that one of two possible options is required). The only way for this situation would be to have that `Required` flag somewhere in the option description and we pick up on it. That would work but it would be ugly.

So we're already in a pickle here anyway. But beside that: The first thing i thought when i saw `[arg]` was that this makes no sense because `[]` is traditionally the notation of an optional argument. I didn't care to see if the description says required or not. It's a description. It means nothing. :) And in our case the argument right now can be required or not, depending on a possibly existing `. Default=` in the option description.

I seem to believe that in the Perl world it is kind of common to have required arguments to options with the `{}` notation while using `[]` for an optional argument. But even if that is untrue we could be discussing to use `<>` for required arguments which seems to be another commonly used syntax.

Or we could say that we don't care if it is `[]`, `{}` or `<>` and the only thing that counts is the word `Required`.

And that brings me to my last point of the exact syntax of that `Required` and also the current `Default`. It is not possible to set a default right now by having multiple lines of description and the last line just says `Default="test"` because there is no `. `. The same would be true for the `Required` flag. Should it be able to stand alone? Should any appearance of the word in any context trigger it effectively forbidding the user to every use that specific word other than for this reason?

It's a bigger issue in general.
So yes, let the discussions begin. :)

My proposal to allow something like automatic validation and the fact that it seems more obvious to the reader of the usage:

```
 -a {arg} description.
 -b {arg} description. Default="b-default"
 -c [arg] description.
 -d [arg] description. Default="d-default"
```

* -a requires an argument and has no default. automatic validation will complain if not set.

* -b looks like it requires an argument but really sets a default. This would be a logic error of the developer but only insofar as the user will be confused by this help. automatic validation won't complain because there will always be an argument set.

* -c has an optional argument. If the script would require -c to be set (developer's own if) it would be a logic error of the developer and automatic validation would not complain if it is not set. The reader of this help would be confused though.

* -d has an optional argument with a default specified. Automatic validation won't care.

Finally I propose that there is no such thing as a required option without an argument because the whole construct, as the name implies, is optional by definition. Only an argument to an option can be optional or required.

**Comment by mstreuhofer** [comment]
reworked the PR. It now supports both ways of defining an argument to be required. Either the single word sentence `Required.` is found (on any line of a possibly multi-line description) or `{arg}` is used; automatic validation kicks in.

An option without argument but `Required.` in the description won't trigger anything.

It is now also supported to have `Default=` on its own line all by itself. The same is true for `Required.`

The only thing which is not supported is to have an option with an argument with no description besides `Default=` or `Required.` on the first and only line of where the description should be.

**Comment by zbeekman** [comment]
I like it! I'll review in detail tomorrow... sorry this is stalled out, I've been swamped

**Comment by mstreuhofer** [comment]
heads up. this PR will not apply cleanly once #70 and #71 is merged.
i'll rework it after the mentioned PRs are in.

**Comment by zbeekman** [comment]
@mstreuhofer would you mind fixing the conflict (you can just merge master into the branch, or rebase onto master, and then push back up)

**Comment by mstreuhofer** [comment]
alright. now this PR applies cleanly and works as expected.
let me know if there is something to change or discuss about it.

**Comment by zbeekman** [comment]
I still need to review it in detail. Also, @kvz, it seems that some of the node packages on OS X are outdated...

**Comment by mstreuhofer** [comment]
now i broke git. ;)

```
remote: Unexpected system error after push was received.
remote: These changes may not be reflected on github.com!
```

i'll close this PR and create a new branch followed by a new PR

**Comment by kvz** [comment]
> I still need to review it in detail. Also, @kvz, it seems that some of the node packages on OS X are outdated...

Handling in https://github.com/kvz/bash3boilerplate/issues/75

**Pull request closed without merging**
